version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Shanghai
    groups:
      patch-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - patch
    assignees:
      - DCjanus
    open-pull-requests-limit: 5

  - package-ecosystem: bun
    directory: "/tools/js-ref"
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Shanghai
    groups:
      patch-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - patch
    assignees:
      - DCjanus
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Shanghai
    groups:
      patch-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - patch
    assignees:
      - DCjanus
    open-pull-requests-limit: 5
