version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bun"
    directory: "/tools/js-ref"
    schedule:
      interval: "weekly"
