use std::{env, fs, path::Path, path::PathBuf};

use base64::{Engine as _, engine::general_purpose::STANDARD};

struct TableSpec {
    file_name: &'static str,
    ident: &'static str,
    font_name: &'static str,
}

struct StylePreviewSpec {
    variant: &'static str,
    file_name: &'static str,
    alt: &'static str,
}

fn assert_valid_ranges(rows: &[(u32, u32, f32)], file_name: &str) {
    for (index, (lower, upper, _)) in rows.iter().copied().enumerate() {
        assert!(
            lower <= upper,
            "invalid anafanafo range in {file_name}: lower {lower} > upper {upper}"
        );

        if index > 0 {
            let (_, previous_upper, _) = rows[index - 1];
            assert!(
                previous_upper < lower,
                "overlapping or unsorted anafanafo ranges in {file_name}: previous upper {previous_upper}, current lower {lower}"
            );
        }
    }
}

fn generate_style_preview_docs(manifest_dir: &Path) -> String {
    let previews = [
        StylePreviewSpec {
            variant: "Plastic",
            file_name: "plastic.svg",
            alt: "plastic badge preview",
        },
        StylePreviewSpec {
            variant: "Flat",
            file_name: "flat.svg",
            alt: "flat badge preview",
        },
        StylePreviewSpec {
            variant: "FlatSquare",
            file_name: "flat-square.svg",
            alt: "flat-square badge preview",
        },
        StylePreviewSpec {
            variant: "ForTheBadge",
            file_name: "for-the-badge.svg",
            alt: "for-the-badge preview",
        },
        StylePreviewSpec {
            variant: "Social",
            file_name: "social.svg",
            alt: "social badge preview",
        },
    ];

    let mut markdown = String::new();
    markdown.push_str("Visual style used for badge rendering.\n\n");
    markdown.push_str(
        "<!-- Generated by build.rs from tracked SVG assets in docs/style-previews/. -->\n\n",
    );
    markdown.push_str("| Variant | Preview |\n");
    markdown.push_str("| --- | --- |\n");

    for preview in previews {
        let path = manifest_dir
            .join("docs/style-previews")
            .join(preview.file_name);
        println!("cargo:rerun-if-changed={}", path.display());

        let svg = fs::read(&path).unwrap_or_else(|_| {
            panic!("failed to read tracked style preview SVG {}", path.display())
        });
        let data_url = format!(
            "data:image/svg+xml;base64,{}",
            STANDARD.encode(svg.as_slice())
        );
        markdown.push_str(&format!(
            "| `{}` | <img alt=\"{}\" src=\"{}\" /> |\n",
            preview.variant, preview.alt, data_url
        ));
    }

    markdown
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing manifest dir"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));

    println!("cargo:rerun-if-changed=build.rs");

    let tables = [
        TableSpec {
            file_name: "verdana-10px-normal.json",
            ident: "VERDANA_10",
            font_name: "10px Verdana",
        },
        TableSpec {
            file_name: "verdana-10px-bold.json",
            ident: "VERDANA_10_BOLD",
            font_name: "bold 10px Verdana",
        },
        TableSpec {
            file_name: "verdana-11px-normal.json",
            ident: "VERDANA_11",
            font_name: "11px Verdana",
        },
        TableSpec {
            file_name: "helvetica-11px-bold.json",
            ident: "HELVETICA_11_BOLD",
            font_name: "bold 11px Helvetica",
        },
    ];

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs; do not edit by hand.\n");
    generated.push_str("//\n");
    generated.push_str("// This file is derived from JSON width tables under `data/anafanafo/`.\n");
    generated.push_str("// Those JSON files are copied from upstream `metabolize/anafanafo` and\n");
    generated.push_str("// intentionally remain the source of truth in this repository.\n\n");

    for table in tables {
        let path = manifest_dir.join("data/anafanafo").join(table.file_name);
        println!("cargo:rerun-if-changed={}", path.display());

        let raw = fs::read_to_string(&path).expect("failed to read anafanafo width table JSON");
        let rows: Vec<(u32, u32, f32)> =
            serde_json::from_str(&raw).expect("invalid anafanafo width table JSON");
        assert_valid_ranges(&rows, table.file_name);

        let em_width = rows
            .iter()
            .find(|(lower, upper, _)| *lower <= 'm' as u32 && 'm' as u32 <= *upper)
            .map(|(_, _, width)| *width)
            .expect("anafanafo width table must contain `m`");

        generated.push_str(&format!(
            "// Source: data/anafanafo/{}\n// Font: {}\n// Rows: {}\n// Em width (`m`): {:?}\n",
            table.file_name,
            table.font_name,
            rows.len(),
            em_width
        ));
        generated.push_str(&format!(
            "static {}_DATA: &[WidthTableRange] = &[\n",
            table.ident
        ));
        for (lower, upper, width) in rows {
            generated.push_str(&format!(
                "    WidthTableRange::new({lower}, {upper}, {width:?}),\n"
            ));
        }
        generated.push_str("];\n");
        generated.push_str(&format!(
            "static {}_CONSUMER: CharWidthTableConsumer = CharWidthTableConsumer::new_static({}_DATA, {em_width:?});\n\n",
            table.ident, table.ident
        ));
    }

    fs::write(out_dir.join("anafanafo_tables.rs"), generated)
        .expect("failed to write generated anafanafo tables");
    fs::write(
        out_dir.join("style-previews.md"),
        generate_style_preview_docs(&manifest_dir),
    )
    .expect("failed to write generated style preview markdown");
}
