use std::{env, fs, path::PathBuf};

struct TableSpec {
    file_name: &'static str,
    ident: &'static str,
    font_name: &'static str,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing manifest dir"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));

    println!("cargo:rerun-if-changed=build.rs");

    let tables = [
        TableSpec {
            file_name: "verdana-10px-normal.json",
            ident: "VERDANA_10",
            font_name: "10px Verdana",
        },
        TableSpec {
            file_name: "verdana-10px-bold.json",
            ident: "VERDANA_10_BOLD",
            font_name: "bold 10px Verdana",
        },
        TableSpec {
            file_name: "verdana-11px-normal.json",
            ident: "VERDANA_11",
            font_name: "11px Verdana",
        },
        TableSpec {
            file_name: "helvetica-11px-bold.json",
            ident: "HELVETICA_11_BOLD",
            font_name: "bold 11px Helvetica",
        },
    ];

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs; do not edit by hand.\n");
    generated.push_str("//\n");
    generated.push_str("// This file is derived from JSON width tables under `data/anafanafo/`.\n");
    generated.push_str("// Those JSON files are copied from upstream `metabolize/anafanafo` and\n");
    generated.push_str("// intentionally remain the source of truth in this repository.\n\n");

    for table in tables {
        let path = manifest_dir.join("data/anafanafo").join(table.file_name);
        println!("cargo:rerun-if-changed={}", path.display());

        let raw = fs::read_to_string(&path).expect("failed to read anafanafo width table JSON");
        let rows: Vec<(u32, u32, f32)> =
            serde_json::from_str(&raw).expect("invalid anafanafo width table JSON");

        let em_width = rows
            .iter()
            .find(|(lower, upper, _)| *lower <= 'm' as u32 && 'm' as u32 <= *upper)
            .map(|(_, _, width)| *width)
            .expect("anafanafo width table must contain `m`");

        generated.push_str(&format!(
            "// Source: data/anafanafo/{}\n// Font: {}\n// Rows: {}\n// Em width (`m`): {:?}\n",
            table.file_name,
            table.font_name,
            rows.len(),
            em_width
        ));
        generated.push_str(&format!(
            "static {}_DATA: &[WidthTableRange] = &[\n",
            table.ident
        ));
        for (lower, upper, width) in rows {
            generated.push_str(&format!(
                "    WidthTableRange::new({lower}, {upper}, {width:?}),\n"
            ));
        }
        generated.push_str("];\n");
        generated.push_str(&format!(
            "static {}_CONSUMER: CharWidthTableConsumer = CharWidthTableConsumer::new_static({}_DATA, {em_width:?});\n\n",
            table.ident, table.ident
        ));
    }

    fs::write(out_dir.join("anafanafo_tables.rs"), generated)
        .expect("failed to write generated anafanafo tables");
}
