name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - uses: oven-sh/setup-bun@v2

      - uses: taiki-e/install-action@v2
        with:
          tool: just

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Check formatting
        run: cargo fmt --check

      - name: Run test suite
        run: just test
